# Generated by Django 3.2.8 on 2021-11-01 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('total_points', models.FloatField(blank=True, null=True)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('test_status', models.CharField(choices=[('STARTED', 'Started'), ('FINISHED', 'Finished'), ('CANCELLED', 'Cancelled'), ('PASSED', 'Passed'), ('NA', 'Not available')], default='NA', max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
