# Generated by Django 3.2.8 on 2021-11-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('test_history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='given_answers',
            field=models.ManyToManyField(to='answers.Answer'),
        ),
    ]
