# Generated by Django 3.2.8 on 2021-11-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_history', '0002_testhistory_given_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testhistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
