# Generated by Django 3.2.8 on 2021-11-16 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_history', '0003_alter_testhistory_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testhistory',
            options={'verbose_name_plural': 'Test histories'},
        ),
    ]
