# Generated by Django 3.2.8 on 2021-12-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_history', '0005_testhistory_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testhistory',
            name='mark',
        ),
    ]
