const TESTS = "[TESTS]";

const ACTION_TYPES = {
  CREATE_NEW_QUESTION: `${TESTS} CREATE_NEW_QUESTION`,
  CREATE_NEW_ANSWER: `${TESTS} CREATE_NEW_ANSWER`,
  ADD_NEW_ANSWER: `${TESTS} ADD_NEW_ANSWER`,
  SHOW_SUCCESS_TOAST: `${TESTS} SHOW_SUCCESS_TOAST`,
  CLOSE_SUCCESS_TOAST: `${TESTS} HIDE_SUCCESS_TOAST`,
  FETCH_ALL_QUESTIONS: `${TESTS} FETCH_ALL_QUESTIONS`,
  SET_ALL_QUESTIONS: `${TESTS} SET_ALL_QUESTIONS`,
  FETCH_ALL_SECTIONS: `${TESTS} FETCH_ALL_SECTIONS`,
  SET_ALL_SECTIONS: `${TESTS} SET_ALL_SECTIONS`,
  SAVE_SECTION: `${TESTS} SAVE_SECTION`,
  SAVE_TEST: `${TESTS} SAVE_TEST`,
  FETCH_TEST: `${TESTS} FETCH_TEST`,
  SET_TEST: `${TESTS} SET_TEST`,
};

export default ACTION_TYPES;
