version: "3.9"
   
services:
  nginx:
    image: nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/index.html:/app/html:ro

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=SotisDB
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    environment:
      - 'DATABASE_ENGINE=django.db.backends.postgresql'
      - 'DATABASE_NAME=SotisDB'
      - 'DATABASE_USER=postgres'
      - 'DATABASE_PASSWORD=postgres'
      - 'DATABASE_HOST=db'
      - 'DATABASE_PORT=5432'
      - 'FRONTEND_URL=http://localhost:3000'
      - 'EMAIL_HOST=localhost'
      - 'EMAIL_PORT=1025'
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mailhog
    links:
      - db

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui

