version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=SotisDB
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    

  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/backend
    environment:
      - 'DATABASE_ENGINE=django.db.backends.postgresql'
      - 'DATABASE_NAME=SotisDB'
      - 'DATABASE_USER=postgres'
      - 'DATABASE_PASSWORD=postgres'
      - 'DATABASE_HOST=db'
      - 'DATABASE_PORT=5432'
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

