# Generated by Django 3.2.8 on 2021-12-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('connections', '0001_initial'),
        ('tests', '0004_alter_test_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('connections', models.ManyToManyField(blank=True, null=True, to='connections.Connection')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.test')),
            ],
        ),
    ]
