# Generated by Django 3.2.8 on 2021-12-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_spaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='computed',
            field=models.BooleanField(default=False),
        ),
    ]
