# Generated by Django 3.2.8 on 2021-12-13 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_domainconnection'),
        ('knowledge_spaces', '0002_knowledgespace_computed'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='domain_connections',
            field=models.ManyToManyField(blank=True, null=True, to='connections.DomainConnection'),
        ),
    ]
