# Generated by Django 3.2.8 on 2022-01-23 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_domainconnection_test'),
        ('knowledge_spaces', '0003_knowledgespace_domain_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgespace',
            name='connections',
            field=models.ManyToManyField(to='connections.Connection'),
        ),
        migrations.AlterField(
            model_name='knowledgespace',
            name='domain_connections',
            field=models.ManyToManyField(to='connections.DomainConnection'),
        ),
    ]
