# Generated by Django 3.2.8 on 2022-01-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0003_domainconnection_test'),
        ('tests', '0010_auto_20220123_2244'),
        ('knowledge_spaces', '0005_knowledgespace_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgespace',
            name='connections',
            field=models.ManyToManyField(null=True, to='connections.Connection'),
        ),
        migrations.AlterField(
            model_name='knowledgespace',
            name='domain_connections',
            field=models.ManyToManyField(blank=True, to='connections.DomainConnection'),
        ),
        migrations.AlterField(
            model_name='knowledgespace',
            name='tests',
            field=models.ManyToManyField(blank=True, related_name='contained_tests', to='tests.Test'),
        ),
    ]
