# Generated by Django 3.2.8 on 2022-02-02 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
        ('knowledge_spaces', '0007_alter_knowledgespace_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgespace',
            name='problem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='problem.problem'),
        ),
    ]
