const TESTS = "[TESTS]";

const ACTION_TYPES = {
  ADD_QUESTION: `${TESTS} ADD_QUESTION`,
  CREATE_NEW_ANSWER: `${TESTS} CREATE_NEW_ANSWER`,
  ADD_NEW_ANSWER: `${TESTS} ADD_NEW_ANSWER`,
};

export default ACTION_TYPES;
