# Generated by Django 3.2.8 on 2021-11-23 20:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0006_alter_question_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_question', to='questions.question')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_question', to='questions.question')),
            ],
        ),
    ]
