# Generated by Django 3.2.8 on 2021-12-13 19:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20211211_1141'),
        ('connections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_domain', to='questions.domain')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_domain', to='questions.domain')),
            ],
        ),
    ]
