# Generated by Django 3.2.8 on 2021-10-31 12:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.TextField(max_length=200)),
                ('time_dependant', models.BooleanField()),
                ('min_choices', models.IntegerField(blank=True, null=True)),
                ('max_choices', models.IntegerField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('all_answers', models.ManyToManyField(related_name='all_answers', to='answers.Answer')),
                ('correct_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct', to='answers.answer')),
            ],
        ),
    ]
