# Generated by Django 3.2.8 on 2021-10-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='none', max_length=500),
            preserve_default=False,
        ),
    ]
