# Generated by Django 3.2.8 on 2021-10-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('questions', '0002_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='all_answers',
            field=models.ManyToManyField(blank=True, related_name='all_answers', to='answers.Answer'),
        ),
    ]
