# Generated by Django 3.2.8 on 2021-11-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('questions', '0003_alter_question_all_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.ManyToManyField(related_name='correct', to='answers.Answer'),
        ),
    ]
