# Generated by Django 3.2.8 on 2021-11-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_question_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='identifier',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
