# Generated by Django 3.2.8 on 2021-12-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
        ('questions', '0006_alter_question_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='all_answers',
            field=models.ManyToManyField(blank=True, related_name='questions', to='answers.Answer'),
        ),
    ]
