# Generated by Django 3.2.8 on 2021-12-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_auto_20211211_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='max_correct_answers',
            field=models.IntegerField(default=0),
        ),
    ]
