# Generated by Django 3.2.8 on 2021-12-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_auto_20211226_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='max_correct_answers',
            field=models.IntegerField(default=1),
        ),
    ]
