# Generated by Django 3.2.8 on 2021-10-31 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.TextField(max_length=200)),
                ('text', models.TextField(max_length=500)),
            ],
        ),
    ]
