# Generated by Django 3.2.8 on 2021-12-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_test_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='sort_by_computed_ks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='sort_by_ks',
            field=models.BooleanField(default=False),
        ),
    ]
