# Generated by Django 3.2.8 on 2022-01-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_color'),
        ('tests', '0005_auto_20211214_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
