# Generated by Django 3.2.8 on 2022-01-16 09:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_test_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='expiration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
