# Generated by Django 3.2.8 on 2022-01-16 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_test_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
